swagger: "2.0"
info:
  description: "This is a simple AWS API Gateway + AWS Lambda server."
  version: "1.0.0"
  title: "Node.js in AWS Cloud"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "TBD"
basePath: "/v2"
tags:
- name: "products"
  description: "Get access to products"
schemes:
- "https"
- "http"
paths:
  /products:
    get:
      tags:
      - "products"
      summary: "Returns all products"
      operationId: "getProductsList"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: '#/definitions/Product'
        "500":
          description: "Internal Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      tags:
      - "products"
      summary: "Create product"
      operationId: "createProduct"
      produces:
      - "application/json"
      parameters:
        - in: body
          name: product
          required: true
          schema:
            $ref: '#/definitions/Product'
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        "500":
          description: "Internal Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /products/{productId}:
    get:
      tags:
      - "products"
      summary: "Find product by ID"
      operationId: "getProductsById"
      produces:
      - "application/json"
      parameters:
      - name: "productId"
        in: "path"
        description: "ID of product that needs to be fetched"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        "404":
          description: "Product not found"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  Stock:
    type: "object"
    properties:
      product_id:
        type: "string"
        format: "uuid"
      count:
        type: "number"
        format: "integer"
  Product:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      title:
        type: "string"
      description:
        type: "string"
      price:
        type: "number"
        format: "integer"
      stock:
        "$ref": "#/definitions/Stock"
    xml:
      name: "Order"
  ErrorResponse:
    type: "object"
    properties:
      errorMessage:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"